// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PEnfQRyo5DBRV_-VpBDOfGrDsi3TdRk',
    appId: '1:213785029624:web:e6fb029c659e256620440d',
    messagingSenderId: '213785029624',
    projectId: 'ipo-lens',
    authDomain: 'ipo-lens.firebaseapp.com',
    storageBucket: 'ipo-lens.firebasestorage.app',
    measurementId: 'G-DS3RJXE6L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BZ5F7f4yopiv33s7GT-AuvxeCHWWbl4',
    appId: '1:213785029624:android:179c6fc599670d8220440d',
    messagingSenderId: '213785029624',
    projectId: 'ipo-lens',
    storageBucket: 'ipo-lens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBix_8rLk1Bs90F_4uMGOcexrwOErQC1hA',
    appId: '1:213785029624:ios:d5cde838cd9f458920440d',
    messagingSenderId: '213785029624',
    projectId: 'ipo-lens',
    storageBucket: 'ipo-lens.firebasestorage.app',
    iosBundleId: 'com.example.ipoLens',
  );

}